global_costmap:
   global_frame: odom
   robot_base_frame: arips_base
   update_frequency: 3.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 20.0
   height: 20.0
   resolution: 0.1
   transform_tolerance: 0.5
