topo_planner:
  global_frame_id: map
  planner_type: PathRepairTopoPlanner
  
DijkstraTopoPlanner:
  dijkstra_discovery: true
  dijkstra_region_heuristics: true
  dijkstra_back_heuristics: false

PathRepairTopoPlanner: []

OpenDoor:
  door_handle_approach_x_offset: 0.14
  door_handle_approach_y_offset: 0.02
  hook_servo_angle: 100