base_local_planner: robotino_local_planner/RobotinoLocalPlanner
#base_local_planner: base_local_planner/TrajectoryPlannerROS
# controller_frequency: 10.0
RobotinoLocalPlanner:
  max_linear_vel: 0.2
  mix_linear_vel: 0.1
  max_rotation_vel: 0.2
  min_rotation_vel: 0.1

  yaw_goal_tolerance: 10
  xy_goal_tolerance: 0.10
  
  heading_lookahead: 0.3
  num_window_points: 10
  
