obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.25
inflation_radius: 0.6

observation_sources: scan 

scan: {data_type: LaserScan, topic: /narrow_scan, marking: true, clearing: true}

