#base_local_planner: robotino_local_planner/RobotinoLocalPlanner
base_local_planner: base_local_planner/TrajectoryPlannerROS
controller_frequency: 5.0
RobotinoLocalPlanner:
  max_linear_vel: 0.2
  mix_linear_vel: 0.1
  max_rotation_vel: 1.0
  min_rotation_vel: 0.3

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 5
  
  heading_lookahead: 0.3
  num_window_points: 10
  
TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.5
  
  heading_lookahead: 0.8
  
  holonomic_robot: false
  yaw_goal_tolerance: 10
