obstacle_range: 2.5
raytrace_range: 3.0
max_obstacle_height: 1.0
min_obstacle_height: 0.3
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.15
inflation_radius: 0.15

observation_sources: scan 
#point_cloud
scan: {data_type: LaserScan, topic: /narrow_scan, marking: true, clearing: true}
#point_cloud: {data_type: PointCloud2, topic: /cloud_throttled, marking: true, clearing: true, min_obstacle_height:  0.07, max_obstacle_height: 1.0,}

