<?xml version="1.0"?>
<robot name="arips" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_height" value="0.15"/>
    <xacro:property name="base_above_ground" value="0.05"/>
    <xacro:property name="base_radius" value="0.2"/>
    <xacro:property name="wheel_base" value="0.34"/>
    <xacro:property name="wheel_thick" value="0.03"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="front_wheel_gap" value="0.003"/>
    <xacro:property name="wheel_damping_factor" value="0.2"/>
    
    <xacro:property name="camera_name" value="kinect"/>
    
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>50</updateRate>
            <leftJoint>left_wheel_joint</leftJoint>
            <rightJoint>right_wheel_joint</rightJoint>
            <wheelSeparation>${wheel_base}</wheelSeparation>
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <torque>5</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>arips_base</robotBaseFrame>
            <publishWheelTF>true</publishWheelTF>
            <publishTf>false</publishTf>
            <legacyMode>false</legacyMode>
            
            <odometrySource>encoder</odometrySource>
        </plugin>
    </gazebo>
    
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/arips</robotNamespace>
        </plugin>
    </gazebo>
    
    
    <gazebo reference="arips_base">
        <sensor type="ray" name="lidar_sensor">
        <pose>0 0 0.2 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>8</update_rate>
        <ray>
            <scan>
            <horizontal>
                <samples>360</samples>
                <resolution>1</resolution>
                <min_angle>${-PI}</min_angle>
                <max_angle>${PI}</max_angle>
            </horizontal>
            </scan>
            <range>
            <min>0.21</min>
            <max>15.0</max>
            <resolution>0.01</resolution>
            </range>
            <noise>
            <type>gaussian</type>
            <!-- Noise parameters based on published spec for Hokuyo laser
                achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                reading. -->
            <mean>0.0</mean>
            <stddev>0.02</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_laser.so">
            <topicName>/scan</topicName>
            <frameName>arips_base</frameName>
        </plugin>
        </sensor>
    </gazebo>
    
      <gazebo reference="arips_base">
        <mu1>0.0001</mu1>
        <mu2>0.0001</mu2>
    </gazebo>
    
    <!-- Use slightly different friction for individual wheels to be more realistic -->
    <gazebo reference="left_wheel">
        <mu1>0.81</mu1>
        <mu2>0.81</mu2>
    </gazebo>
    
    <gazebo reference="right_wheel">
        <mu1>0.81</mu1>
        <mu2>0.81</mu2>
    </gazebo>
    
    <gazebo reference="kinect_link">
        <sensor name="kinect_camera" type="depth">
            <update_rate>20</update_rate>
            <camera>
            <horizontal_fov>1.047198</horizontal_fov>
            <image>
                <width>320</width>
                <height>240</height>
                <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.04</near>
                <far>25</far>
            </clip>
            </camera>
            <plugin name="kinect_plugin" filename="libgazebo_ros_openni_kinect.so">
            <baseline>0.2</baseline>
            <alwaysOn>true</alwaysOn>
            <updateRate>0</updateRate>
            <cameraName>${camera_name}_ir</cameraName>
            <imageTopicName>/${camera_name}/color/image_raw</imageTopicName>
            <cameraInfoTopicName>/${camera_name}/color/camera_info</cameraInfoTopicName>
            <depthImageTopicName>/${camera_name}/depth/image_raw</depthImageTopicName>
            <depthImageInfoTopicName>/${camera_name}/depth/camera_info</depthImageInfoTopicName>
            <pointCloudTopicName>/${camera_name}/depth/points</pointCloudTopicName>
            <frameName>kinect_link</frameName>
            <pointCloudCutoff>0.5</pointCloudCutoff>
            <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
            <distortionK1>0.00000001</distortionK1>
            <distortionK2>0.00000001</distortionK2>
            <distortionK3>0.00000001</distortionK3>
            <distortionT1>0.00000001</distortionT1>
            <distortionT2>0.00000001</distortionT2>
            <CxPrime>0</CxPrime>
            <Cx>0</Cx>
            <Cy>0</Cy>
            <focalLength>0</focalLength>
            <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>

    
    
  <link name="arips_base">
      
    <visual>
        
      <geometry>
        <mesh filename="package://arips_description/models/robot_body.dae" />
      </geometry>
      <origin rpy="0 0 -1.57075"/>
    </visual>
    
    <!-- rear wheel
    <visual>
     <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="${-base_radius + wheel_radius} 0 ${wheel_radius}" rpy="0 0 0"/>
    </visual>
    -->
    
    <collision>
        <geometry>
            <cylinder radius="${base_radius}" length="${base_height}"/>
        </geometry>
        <origin xyz="0 0 ${base_height/2 + base_above_ground}" rpy="0 0 0"/>
    </collision>
    
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="${-base_radius + wheel_radius + 0.001} 0 ${wheel_radius}" rpy="0 0 0"/>
    </collision>
    
    <collision>
        <geometry>
            <sphere radius="${wheel_radius}"/>
        </geometry>
        <origin xyz="${base_radius - wheel_radius - 0.001} 0 ${wheel_radius + front_wheel_gap}" rpy="0 0 0"/>
    </collision>
    
    <inertial>
      <origin xyz="-0.05 0 ${base_height/2 + base_above_ground}" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="0.01625" ixy="0.0" ixz="0.0" iyy="0.01625" iyz="0.0" izz="0.03"/>
    </inertial>
  </link>
  
  <link name="right_wheel">
      <!--
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
      -->
    
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.0007" ixy="0.0" ixz="0.0" iyy="0.0007" iyz="0.0" izz="0.00125"/>
    </inertial>
  </link>
  
  <joint name="right_wheel_joint" type="continuous">
    <parent link="arips_base"/>
    <child link="right_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 -${wheel_base/2} ${wheel_radius}" rpy="${-PI/2} 0 0"/>
    
    <dynamics damping="${wheel_damping_factor}"/>
  </joint>
  
  
  <link name="left_wheel">
      <!--
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
      -->
    
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thick}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.0007" ixy="0.0" ixz="0.0" iyy="0.0007" iyz="0.0" izz="0.00125"/>
    </inertial>
  </link>
  
  <joint name="left_wheel_joint" type="continuous">
    <parent link="arips_base"/>
    <child link="left_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 ${wheel_base/2} ${wheel_radius}" rpy="${-PI/2} 0 0"/>
    
    <dynamics damping="${wheel_damping_factor}"/>
  </joint>
  
  
  
  <link name="kinect_link">
    <visual>
      <geometry>
        <mesh filename="package://arips_description/models/robot_kinect.dae" />
      </geometry>
    </visual>
    
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.06 0.2 0.03"/>
      </geometry>
    </collision>
    
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.0007" ixy="0.0" ixz="0.0" iyy="0.0007" iyz="0.0" izz="0.00125"/>
    </inertial>
  </link>

  <joint name="kinect_joint" type="revolute">
    <limit effort="10.0" lower="-1" upper="1" velocity="0.2"/>
    <parent link="arips_base"/>
    <child link="kinect_link"/>
    <origin xyz="-0.14 0 0.74" rpy="0 0 0"/>
    <axis xyz="0 1 0" />
    
    <dynamics damping="0.07"/>
  </joint>
  

  
  <transmission name="kinect_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="kinect_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="kinect_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  
    <!--
  <joint name="base_to_arm" type="fixed">
    <parent link="arips_base"/>
    <child link="arm_arips_base"/>
    <origin rpy="-0.028 0 0" xyz="0.163 -0.006 0.055"/>
  </joint>
  
  <include filename="$(find arips_arm_description)/urdf/arips_arm.xacro" />
  -->
  
</robot>
