planner_frequency: 0.15
controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.08
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.5
  acc_lim_th: 0.25
  acc_lim_x: 0.20
  acc_lim_y: 0.20

  holonomic_robot: false
  yaw_goal_tolerance: 10
  xy_goal_tolerance: 0.15
  goal_distance_bias: 1.5
  path_distance_bias: 3.0
  sim_time: 2.0
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

