obstacle_range: 1.5
raytrace_range: 2.0
max_obstacle_height: 2.0
min_obstacle_height: 1.0
robot_radius: 0.25
inflation_radius: 0.25
observation_sources: scan 
# point_cloud
scan: {data_type: LaserScan, topic: /narrow_scan, marking: true, clearing: true}
# point_cloud: {data_type: PointCloud2, topic: /cloud_throttled, marking: true, clearing: true, min_obstacle_height:  0.07, max_obstacle_height: 1.0,}
