global_costmap:
  publish_frequency: 1.0
  #rolling_window: true
  #width: 600
  #height: 600
  global_frame: map
  robot_base_frame: arips_base
  robot_radius: 0.2
  transform_tolerance: 1.0
  inflation_radius: 0.5
  update_frequency: 2.0

  plugins:
      # - {name: slam_map,       type: "costmap_2d::StaticLayer"}
      - {name: door_overlay,   type: "costmap_2d::StaticLayer"}
      - {name: obstacles,   type: "costmap_2d::VoxelLayer"}
      - {name: inflaton,       type: "costmap_2d::InflationLayer"}
  door_overlay:
      map_topic: /flat_layer_map1_overlay
      use_maximum: true
  obstacles:
      observation_sources: scan
      scan: {data_type: LaserScan, clearing: true, marking: true, topic: /scan}
      map: /map

  #slam_map:
  #    map_topic: /flat_layer_map1_fake
  #    lethal_cost_threshold: 50
  #    # track_unknown_space: false
  #    #unknown_cost_value: 100
  #    #use_maximum: true
  inflaton:
      inflation_radius: 0.5
        

local_costmap:
  map_topic: /flat_layer_map1
  global_frame: odom
  robot_base_frame: arips_base
  robot_radius: 0.2
  inflation_radius: 0.5
  map_type: costmap
  observation_sources: scan

  static_map: false
  rolling_window: true
  width: 1.5
  height: 1.5
  resolution: 0.015

  update_frequency: 10.0
  publish_frequency: 2.5
  transform_tolerance: 1.0
  
  cost_scaling_factor: 5.0

  #robot_base_frame: base_link
  #obstacle_range: 3.5
  #raytrace_range: 5.0
  #robot_radius: 0.22
  #inflation_radius: 0.5
  #max_obstacle_height: 1.0
  #observation_sources: scan


  scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#  global_frame: flat_layer_map1_frame
#  update_frequency: 10.0
#  publish_frequency: 2.5
#  static_map: false
#  rolling_window: true
#  width: 1.5
#  height: 1.5
#  resolution: 0.025
#  publish_voxel_map: true
#  map_type: costmap
#  z_resolution: 0.1
#  z_voxels: 9
#  unknown_threshold: 8

navfn_planner:
  allow_unknown: false
  visualize_potential: true

AripsPlannerROS:
  use_dwa: false

  # Robot Configuration Parameters - Kobuki
  max_vel_x: 0.4
  min_vel_x: -0.2

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  max_vel_trans: 0.3 # choose slightly less than the base's capability
  min_vel_trans: 0.03  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.2

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_vel_theta: 2.0  # choose slightly less than the base's capability
  min_vel_theta: 0.2  # this is the min angular velocity when there is negligible translational velocity
  theta_stopped_vel: 0.3

  acc_lim_x: 1.0 # maximum is theoretically 2.0, but we
  acc_lim_theta: 1.0
  acc_lim_y: 0.0      # diff drive robot

  sum_scores: false

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1  # 0.05
  xy_goal_tolerance: 0.1  # 0.10
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 1.0       # 1.7
  vx_samples: 4       # 3
  vy_samples: 1       # diff drive robot, there is only one sample
  vtheta_samples: 15  # 20

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 24.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.01            # 0.01   - weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 # 0.325  - how far along to place an additional scoring point
  stop_time_buffer: 0.2         # 0.2    - amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 0.25           # 0.25   - absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.01       # 0.2    - how much to scale the robot's footprint when at speed.

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # 0.05   - how far to travel before resetting oscillation flags

  # Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom


  # Differential-drive robot configuration - necessary?
  holonomic_robot: false
