parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 0.05020323395729065
            y: -1.93680477142334
            z: -2.384185791015625e-07
          end:
            x: 0.9439178705215454
            y: -1.941192269325256
            z: -9.5367431640625e-07
          frame_id: map
nodes:
  - name: appartement
    type: flat
    node_data:
      x: 240
      y: 240
  - name: map1_node_1
    type: flat
    node_data:
      x: 225
      y: 225
  - name: map1_node_2
    type: flat
    node_data:
      x: 129
      y: 129
  - name: map1_node_3
    type: flat
    node_data:
      x: 370
      y: 370
  - name: map1_node_4
    type: flat
    node_data:
      x: 311
      y: 311
  - name: map1_node_5
    type: flat
    node_data:
      x: 203
      y: 203
edges:
  - name: step_0_appartement_appartement
    type: step
    source: appartement
    target: map1_node_1
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.451425719745665
          y: -1.688771473461559
          z: -2.384185791015625e-07
        end:
          x: 0.5451499965587465
          y: -1.689231592442554
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7088403288650947
          w: -0.7053689730732593
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_1_appartement_appartement
    type: step
    source: map1_node_1
    target: appartement
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.4489711079200895
          y: -2.188765448306042
          z: -2.384185791015625e-07
        end:
          x: 0.542695384733171
          y: -2.189225567287037
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7053689730732593
          w: 0.7088403288650947
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
