parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 0.05020323395729065
            y: -1.93680477142334
            z: -2.384185791015625e-07
          end:
            x: 0.9439178705215454
            y: -1.941192269325256
            z: -9.5367431640625e-07
          frame_id: map
        - name: Step_1
          start:
            x: 2.344362020492554
            y: -3.356512308120728
            z: 2.384185791015625e-07
          end:
            x: 2.349725246429443
            y: -2.560161352157593
            z: 0
          frame_id: map
nodes:
  - name: Arbeitszimmer
    type: flat
    node_data:
      x: 240
      y: 240
  - name: Flur
    type: flat
    node_data:
      x: 129
      y: 129
  - name: Wohnzimmer
    type: flat
    node_data:
      x: 370
      y: 370
edges:
  - name: step_Arbeitszimmer_Flur
    type: step
    source: Arbeitszimmer
    target: Flur
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.4533348977565765
          y: -0.5685608983039856
          z: -2.384185791015625e-07
        end:
          x: 0.5614641904830933
          y: -0.5743050575256348
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7088403288650947
          w: -0.7053689730732593
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_Flur_Arbeitszimmer
    type: step
    source: Flur
    target: Arbeitszimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.445289190181726
          y: -2.938756410572767
          z: -2.384185791015625e-07
        end:
          x: 0.5390134669948075
          y: -2.939216529553762
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7053689730732593
          w: 0.7088403288650947
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_Flur_Wohnzimmer
    type: step
    source: Flur
    target: Wohnzimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.34707853774098
          y: -2.949786780238729
          z: 2.384185791015625e-07
        end:
          x: 1.347054084518304
          y: -2.953417682140679
          z: 0
        orientation:
          x: 0
          y: 0
          z: 0.003367318565516157
          w: -0.9999943305667679
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_Wohnzimmer_Flur
    type: step
    source: Wohnzimmer
    target: Flur
    approach_data:
      approach:
        type: LineArea
        start:
          x: 3.347033182403694
          y: -2.963255978137642
          z: 2.384185791015625e-07
        end:
          x: 3.347008729181017
          y: -2.966886880039592
          z: 0
        orientation:
          x: 0
          y: 0
          z: 0.9999943305667679
          w: 0.003367318565516096
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up