parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
      maps:
        map1:
          planner: NavfnCostsPlanner
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 1.727037310600281
            y: -0.2690128982067108
            z: -3.075599670410156e-05
          end:
            x: 1.715111494064331
            y: 0.4312114715576172
            z: -3.075599670410156e-05
          frame_id: odom
        - name: Step_1
          start:
            x: 2.077819108963013
            y: 2.166691303253174
            z: 0
          end:
            x: 2.84944748878479
            y: 2.175362348556519
            z: 0
          frame_id: odom
nodes:
  - name: map1_node_0
    type: flat
    node_data:
      x: 543
      y: 0
      map: map1
      height: 0
  - name: map1_node_19
    type: flat
    node_data:
      x: 277
      y: 272
      map: map1
      height: 0
  - name: map1_node_3
    type: flat
    node_data:
      x: 316
      y: 241
      map: map1
      height: 0
  - name: map1_node_4
    type: flat
    node_data:
      x: 314
      y: 198
      map: map1
      height: 0
  - name: map1_node_5
    type: flat
    node_data:
      x: 311
      y: 316
      map: map1
      height: 0
  - name: map1_node_71
    type: flat
    node_data:
      x: 239
      y: 347
      map: map1
      height: 0
  - name: map1_node_74
    type: flat
    node_data:
      x: 201
      y: 250
      map: map1
      height: 0
  - name: map1_node_75
    type: flat
    node_data:
      x: 200
      y: 293
      map: map1
      height: 0
edges:
  - name: step_0_map1_node_19_map1_node_4
    type: step
    source: map1_node_3
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.470261980537801
          y: 0.1266718625199365
          z: -3.075599670410156e-05
        end:
          x: 1.471959325685735
          y: 0.02701223477854203
          z: -3.075599670410156e-05
        orientation:
          x: 0
          y: 0
          z: -0.008514784725605936
          w: -0.9999637485634549
        frame_id: odom
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_1_map1_node_4_map1_node_19
    type: step
    source: map1_node_4
    target: map1_node_3
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.970189478978877
          y: 0.1351863385723643
          z: -3.075599670410156e-05
        end:
          x: 1.971886824126812
          y: 0.03552671083096987
          z: -3.075599670410156e-05
        orientation:
          x: 0
          y: 0
          z: 0.9999637485634549
          w: -0.008514784725605996
        frame_id: odom
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_2_map1_node_4_map1_node_5
    type: step
    source: map1_node_4
    target: map1_node_5
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.480603011791454
          y: 1.921201736016012
          z: 0
        end:
          x: 2.45228189789398
          y: 1.920883482219149
          z: 0
        orientation:
          x: 0
          y: 0
          z: 0.7110684298558266
          w: 0.7031228115076124
        frame_id: odom
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_3_map1_node_5_map1_node_4
    type: step
    source: map1_node_5
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.474984699853824
          y: 2.421170169590544
          z: 0
        end:
          x: 2.446663585956349
          y: 2.420851915793681
          z: 0
        orientation:
          x: 0
          y: 0
          z: 0.7031228115076124
          w: -0.7110684298558266
        frame_id: odom
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up