parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 0.05020323395729065
            y: -1.93680477142334
            z: -2.384185791015625e-07
          end:
            x: 0.9439178705215454
            y: -1.941192269325256
            z: -9.5367431640625e-07
          frame_id: map
        - name: Step_1
          start:
            x: 2.344362020492554
            y: -3.356512308120728
            z: 2.384185791015625e-07
          end:
            x: 2.349725246429443
            y: -2.560161352157593
            z: 0
          frame_id: map
nodes:
  - name: Arbeitszimmer
    type: flat
    node_data:
      x: 240
      y: 240
  - name: Flur
    type: flat
    node_data:
      x: 129
      y: 129
  - name: Wohnzimmer
    type: flat
    node_data:
      x: 370
      y: 370
edges:
  - name: step_Arbeitszimmer_Flur
    type: step
    source: Arbeitszimmer
    target: Flur
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.4236942827701569
          y: -1.649402976036072
          z: -4.76837158203125e-07
        end:
          x: 0.5635682344436646
          y: -1.658800840377808
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7088403288650947
          w: -0.7053689730732593
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_Flur_Arbeitszimmer
    type: step
    source: Flur
    target: Arbeitszimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 0.4314599633216858
          y: -2.176870584487915
          z: -2.384185791015625e-07
        end:
          x: 0.5616844892501831
          y: -2.173904180526733
          z: -9.5367431640625e-07
        orientation:
          x: 0
          y: 0
          z: 0.7053689730732593
          w: 0.7088403288650947
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_Flur_Wohnzimmer
    type: step
    source: Flur
    target: Wohnzimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.083136320114136
          y: -3.056083679199219
          z: 2.384185791015625e-07
        end:
          x: 2.074398279190063
          y: -2.935340642929077
          z: -7.152557373046875e-07
        orientation:
          x: 3.325024730084026e-09
          y: 5.605228332208387e-09
          z: 0.03205341129676289
          w: 0.9994861573950089
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_Wohnzimmer_Flur
    type: step
    source: Wohnzimmer
    target: Flur
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.590766429901123
          y: -3.059189796447754
          z: 3.576278686523438e-07
        end:
          x: 2.593931674957275
          y: -3.144510507583618
          z: 5.364418029785156e-07
        orientation:
          x: 0
          y: 0
          z: 0.9999943305667679
          w: 0.003367318565516096
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up