parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
      maps:
        map1:
          planner: NavfnCostsPlanner
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 1.471131086349487
            y: -0.3248428106307983
            z: -3.075599670410156e-05
          end:
            x: 1.470346093177795
            y: 0.3605566918849945
            z: -3.075599670410156e-05
          frame_id: map
        - name: Step_1
          start:
            x: 2.065991640090942
            y: 1.742993474006653
            z: 0
          end:
            x: 2.882935523986816
            y: 1.750364899635315
            z: 0
          frame_id: map
nodes:
  - name: map1_node_0
    type: flat
    node_data:
      x: 543
      y: 0
      map: map1
      height: 0
  - name: map1_node_19
    type: flat
    node_data:
      x: 277
      y: 272
      map: map1
      height: 0
  - name: map1_node_3
    type: flat
    node_data:
      x: 316
      y: 241
      map: map1
      height: 0
  - name: map1_node_4
    type: flat
    node_data:
      x: 314
      y: 198
      map: map1
      height: 0
  - name: map1_node_5
    type: flat
    node_data:
      x: 311
      y: 316
      map: map1
      height: 0
  - name: map1_node_71
    type: flat
    node_data:
      x: 239
      y: 347
      map: map1
      height: 0
  - name: map1_node_74
    type: flat
    node_data:
      x: 201
      y: 250
      map: map1
      height: 0
  - name: map1_node_75
    type: flat
    node_data:
      x: 200
      y: 293
      map: map1
      height: 0
edges:
  - name: step_0_map1_node_19_map1_node_4
    type: step
    source: map1_node_3
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.173327326774597
          y: 0.03372186422348022
          z: -9.179115295410156e-05
        end:
          x: 1.184886813163757
          y: -0.0477389432489872
          z: -6.127357482910156e-05
        orientation:
          x: -4.412136693150339e-10
          y: -6.626700854745699e-09
          z: -0.002894500222004512
          w: 0.9999958109254582
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_1_map1_node_4_map1_node_19
    type: step
    source: map1_node_4
    target: map1_node_3
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.865539073944092
          y: 0.05897101014852524
          z: -3.075599670410156e-05
        end:
          x: 1.861621141433716
          y: -0.04308249428868294
          z: -3.075599670410156e-05
        orientation:
          x: -1.164934927743332e-08
          y: 1.088345269926357e-09
          z: 0.9999241699244812
          w: -0.01231480413312661
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_2_map1_node_4_map1_node_5
    type: step
    source: map1_node_4
    target: map1_node_5
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.447945833206177
          y: 1.493216395378113
          z: 0
        end:
          x: 2.485207507833747
          y: 1.496765954119086
          z: 0
        orientation:
          x: 5.649473544420466e-09
          y: 1.834787801430164e-10
          z: 0.7337894136724727
          w: 0.6793769913547327
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_3_map1_node_5_map1_node_4
    type: step
    source: map1_node_5
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.442883968353271
          y: 2.100311756134033
          z: 0
        end:
          x: 2.509220838546753
          y: 2.103319883346558
          z: 0
        orientation:
          x: 0
          y: 0
          z: 0.7039095093652146
          w: -0.7102896610716102
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up