parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
      maps:
        map1:
          planner: NavfnCostsPlanner
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 1.493298530578613
            y: -0.3006691336631775
            z: 0
          end:
            x: 1.493717551231384
            y: 0.4518000483512878
            z: -4.76837158203125e-07
          frame_id: map
        - name: Step_1
          start:
            x: 2.87273120880127
            y: 1.727324604988098
            z: 4.76837158203125e-07
          end:
            x: 2.064034938812256
            y: 1.715994834899902
            z: 0
          frame_id: map
nodes:
  - name: arbeitszimmer
    type: flat
    node_data:
      x: 270
      y: 235
      map: map1
      height: 0
  - name: wohnung
    type: flat
    node_data:
      x: 218
      y: 235
      map: map1
      height: 0
  - name: wohnzimmer
    type: flat
    node_data:
      x: 224
      y: 330
      map: map1
      height: 0
edges:
  - name: step_0_arbeitszimmer_wohnung
    type: step
    source: arbeitszimmer
    target: wohnung
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.243736386299133
          y: 0.07465887069702148
          z: 0
        end:
          x: 1.244062662124634
          y: -0.003754418343305588
          z: -4.76837158203125e-07
        orientation:
          x: 0
          y: 0
          z: 0.0002784304088860719
          w: -0.999999961238253
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_1_wohnung_arbeitszimmer
    type: step
    source: wohnung
    target: arbeitszimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.743521236135342
          y: 0.09919158911898163
          z: 0
        end:
          x: 1.743494768151163
          y: 0.051660895171035
          z: -4.76837158203125e-07
        orientation:
          x: 0
          y: 0
          z: 0.999999961238253
          w: 0.0002784304088860106
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: up
  - name: step_2_wohnung_wohnzimmer
    type: step
    source: wohnung
    target: wohnzimmer
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.491488218307495
          y: 1.476982474327087
          z: 1.9073486328125e-06
        end:
          x: 2.529549121856689
          y: 1.477324247360229
          z: 4.76837158203125e-07
        orientation:
          x: -4.039354123085081e-09
          y: 5.601585160856573e-09
          z: 0.7285536808032302
          w: 0.6849887109931557
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_3_wohnzimmer_wohnung
    type: step
    source: wohnzimmer
    target: wohnung
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.489840269088745
          y: 1.96656322479248
          z: 9.5367431640625e-07
        end:
          x: 2.496468305587769
          y: 1.971781134605408
          z: 0
        orientation:
          x: 1.059738569851641e-09
          y: -1.742644080371254e-09
          z: -0.6901345329178871
          w: 0.7236810944568123
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up