parser_data:
  node_parser:
    module_flat:
      default_costs:
        distance_factor: 1
        energy_factor: 1
        time_factor: 1
      maps:
        map1:
          planner: NavfnCostsPlanner
  edge_parser:
    module_step:
      default_costs_down:
        distance: 1
        energy: 3
        time: 15
      default_costs_up:
        distance: 1
        energy: 2.5
        time: 15
      default_costs_cross_over:
        distance: 1
        energy: 3
        time: 15
      default_costs_cross_gravel:
        distance: 1
        energy: 1
        time: 10
      step:
        - name: Step_0
          start:
            x: 1.471131086349487
            y: -0.3248428106307983
            z: -3.075599670410156e-05
          end:
            x: 1.470346093177795
            y: 0.3605566918849945
            z: -3.075599670410156e-05
          frame_id: map
        - name: Step_1
          start:
            x: 2.065991640090942
            y: 1.742993474006653
            z: 0
          end:
            x: 2.882935523986816
            y: 1.750364899635315
            z: 0
          frame_id: map
nodes:
  - name: map1_node_0
    type: flat
    node_data:
      x: 543
      y: 0
      map: map1
      height: 0
  - name: map1_node_19
    type: flat
    node_data:
      x: 277
      y: 272
      map: map1
      height: 0
  - name: map1_node_3
    type: flat
    node_data:
      x: 316
      y: 241
      map: map1
      height: 0
  - name: map1_node_4
    type: flat
    node_data:
      x: 314
      y: 198
      map: map1
      height: 0
  - name: map1_node_5
    type: flat
    node_data:
      x: 311
      y: 316
      map: map1
      height: 0
  - name: map1_node_71
    type: flat
    node_data:
      x: 239
      y: 347
      map: map1
      height: 0
  - name: map1_node_74
    type: flat
    node_data:
      x: 201
      y: 250
      map: map1
      height: 0
  - name: map1_node_75
    type: flat
    node_data:
      x: 200
      y: 293
      map: map1
      height: 0
edges:
  - name: step_0_map1_node_19_map1_node_4
    type: step
    source: map1_node_3
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.173322081565857
          y: 0.0409407839179039
          z: -9.179115295410156e-05
        end:
          x: 1.175407767295837
          y: -0.05248664692044258
          z: -6.127357482910156e-05
        orientation:
          x: 8.64730511269495e-09
          y: 7.996919654890659e-09
          z: 0.0272641303537107
          w: 0.9996282645043885
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_1_map1_node_4_map1_node_19
    type: step
    source: map1_node_4
    target: map1_node_3
    approach_data:
      approach:
        type: LineArea
        start:
          x: 1.861236214637756
          y: 0.05466179549694061
          z: -3.075599670410156e-05
        end:
          x: 1.854380965232849
          y: -0.04308817163109779
          z: -6.127357482910156e-05
        orientation:
          x: -1.164934927743332e-08
          y: 1.088345269926357e-09
          z: 0.9999241699244812
          w: -0.01231480413312661
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_0
      step_type: cross_over
  - name: step_2_map1_node_4_map1_node_5
    type: step
    source: map1_node_4
    target: map1_node_5
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.447945833206177
          y: 1.493216395378113
          z: 0
        end:
          x: 2.485207507833747
          y: 1.496765954119086
          z: 0
        orientation:
          x: 5.649473544420466e-09
          y: 1.834787801430164e-10
          z: 0.7337894136724727
          w: 0.6793769913547327
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up
  - name: step_3_map1_node_5_map1_node_4
    type: step
    source: map1_node_5
    target: map1_node_4
    approach_data:
      approach:
        type: LineArea
        start:
          x: 2.460068225860596
          y: 2.08887791633606
          z: 0
        end:
          x: 2.532130718231201
          y: 2.091890573501587
          z: 0
        orientation:
          x: 6.542194283678878e-09
          y: 8.099093556687627e-09
          z: -0.7047366672603085
          w: 0.7094689773477294
        frame_id: map
    exit_data: ~
    edge_data:
      step_name: Step_1
      step_type: up