arips:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

  # Position Controllers ---------------------------------------
  kinect_position_controller:
    type: effort_controllers/JointPositionController
    joint: kinect_joint
    pid: {p: 50.0, i: 0.01, d: 1.0}
