controller_frequency: 30.0
planner_patience: 2.0
controller_patience: 2.0
clearing_rotation_allowed: true
recovery_behavior_enabled: true
planner_frequency: 1.5

base_local_planner: base_local_planner/TrajectoryPlannerROS
# base_local_planner: pose_follower/PoseFollower
# base_local_planner: eband_local_planner/EBandPlannerROS

TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0.05

  max_vel_theta:  0.5
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.6
  
  acc_lim_x: 2.0
  acc_lim_theta: 2.0

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15

# Forward Simulation Parameters
  sim_time: 4.0
  vx_samples: 30
  vtheta_samples: 50

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.3
  gdist_scale: 0.5
  occdist_scale: 0.04
  heading_lookahead: 0.10
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 30
