robot_base_frame: base_link
obstacle_range: 3.5
raytrace_range: 5.0
robot_radius: 0.22
inflation_radius: 0.5
max_obstacle_height: 1.0
observation_sources: scan
transform_tolerance: 5.0

scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
cloud: {data_type: PointCloud2, topic: /camera/cloud_throttled, marking: true, clearing: true, min_obstacle_height: 0.10, max_obstacle_height: 1.0, raytrace_range: 10.0}
