
docking_costmap:
    global_frame: arips_base
    update_frequency: 10.0
    publish_frequency: 2.5
    rolling_window: false
    origin_x: -0.7
    origin_y: -0.5
    width: 1.0
    height: 1.0
    resolution: 0.01
    publish_voxel_map: true
    z_resolution: 0.1
    z_voxels: 9
    unknown_threshold: 8
    robot_base_frame: arips_base
    obstacle_range: 3.5
    raytrace_range: 5.0
    robot_radius: 0.18
    inflation_radius: 0.2
    max_obstacle_height: 1.0
    min_obstacle_height: -0.3
    transform_tolerance: 5.0
    observation_persistence: 0.5
    plugins:
    - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    
    obstacle_layer:
        enabled: true
        observation_sources: scan
        scan: { data_type: LaserScan, topic: /scan, marking: true, clearing: true}
        max_obstacle_height:  0.6
        min_obstacle_height: -0.3
        origin_z:             -0.1
        z_resolution:         0.2
        z_voxels:             2
        unknown_threshold:    15
        mark_threshold:       0
        combination_method:   1
        observation_persistence: 0.5
        track_unknown_space:  true    #true needed for disabling global path planning through unknown space
        obstacle_range: 2.5
        raytrace_range: 3.0
        origin_z: 0.0
        z_voxels: 2
        publish_voxel_map: true
        publish_frequency: 2.5
    
  
    inflation_layer:
        enabled: false
        inflation_radius: 0.0

# cloud: {data_type: PointCloud2, topic: /camera/cloud_throttled, marking: true, clearing: true, min_obstacle_height: 0.10, max_obstacle_height: 1.0, raytrace_range: 10.0}
