local_costmap:
   global_frame: odom
   update_frequency: 5.0
   publish_frequency: 2.5
   static_map: false
   rolling_window: true
   width: 1.5
   height: 1.5
   resolution: 0.03
   publish_voxel_map: true
   map_type: costmap
   z_resolution: 0.1
   z_voxels: 9
   unknown_threshold: 8
