global_frame: odom
robot_base_frame: arips_base
update_frequency: 5.0
publish_frequency: 1.0

#set if you want the voxel map published
publish_voxel_map: false

#set to true if you want to initialize the costmap from a static map
static_map: false

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 5.0
height: 5.0
resolution: 0.05
#end - COMMENT these lines if you set static_map to true

map_type: costmap
track_unknown_space: true

transform_tolerance: 0.3
obstacle_range: 4.0
min_obstacle_height: 0.0
max_obstacle_height: 2.0
raytrace_range: 4.5

robot_radius: 0.25
inflation_radius: 0.5
cost_scaling_factor: 2.0
lethal_cost_threshold: 100
observation_sources: scan
#scan: {data_type: LaserScan, /scan expected_update_rate: 0.4,
#  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}
