###########################################################
# Defines topics services and frames for all modules

### TF frames #############################################
laser_frame: arips_base
robot_frame: arips_base
odometry_frame: odom
offset_frame: offset
map_frame: map

### ROS topics ############################################
map_topic: map
laser_topic: scan

### ROS services ##########################################
map_service: static_map
